"""empty message

Revision ID: 07ae807db89e
Revises: e9a324c84cb3
Create Date: 2023-04-04 12:15:26.747037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07ae807db89e"
down_revision = "e9a324c84cb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletters",
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("newsletters")
    # ### end Alembic commands ###
