"""empty message

Revision ID: 74b7d14b9f93
Revises: dcd2b02d889e
Create Date: 2023-04-04 02:06:16.861552

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74b7d14b9f93"
down_revision = "dcd2b02d889e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts_subscriptions",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("is_subscribed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("contact_id", "subscription_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts_subscriptions")
    # ### end Alembic commands ###
