"""empty message

Revision ID: 9afa0dbf9815
Revises: 07ae807db89e
Create Date: 2023-04-04 12:15:56.548413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9afa0dbf9815"
down_revision = "07ae807db89e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )

    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
