"""empty message

Revision ID: b7a2d25e0e56
Revises: c9588e7033bc
Create Date: 2023-04-04 21:49:13.294955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7a2d25e0e56"
down_revision = "c9588e7033bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attachment", sa.LargeBinary(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.drop_column("attachment")

    # ### end Alembic commands ###
