"""empty message

Revision ID: c0239514fc05
Revises: b7a2d25e0e56
Create Date: 2023-04-05 23:17:07.355820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0239514fc05"
down_revision = "b7a2d25e0e56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulks",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=True),
        sa.Column("repeated", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bulks")
    # ### end Alembic commands ###
