"""empty message

Revision ID: c9588e7033bc
Revises: 518df04afd2e
Create Date: 2023-04-04 12:55:12.221565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9588e7033bc"
down_revision = "518df04afd2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, "templates", ["template_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("template_id")

    # ### end Alembic commands ###
